config/routes.rb
SinapsIt::Application.routes.draw do

  root :to => 'pages#home'
  
  match '/services' => 'pages#services'
  match '/order' => 'pages#orders'
  match '/contacts' => 'pages#contact'
  match '/help' => 'pages#help'
  

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    def home
    @title = "Новости"
    end
  
   def services
     @title = "Услуги"
   end

  def orders
    @title = "Онлайн заказ"
  end
  
  def contact
    @title = "Контакты"
  end
  
  def help
    @title = "Помощь"
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/_footer.html.erb
<br /><br />
<div class="page-header"></div>
<div class="footer">
	<div class="inner">
	<p>
		<address>
			<strong>Sinaps-it</strong><br />
			Тел:  <br/>
			email: <a href="mailto:" >it.sinaps@gmail.com</a><br />
		</address>
	</p>
</div>
</div>

app/views/layouts/_header.html.erb
<div class="topbar">
  <div class="fill">

   <div class="container">

<h3>
<%= link_to 'Sinaps-it', '#' %>
</h3>
<ul>
<li><%= link_to 'Новости', root_path %></li>
<li><%= link_to 'Услуги', services_path %></li>
<li><%= link_to 'Online-заказ', order_path %></li>
<li><%= link_to 'Контакты', contacts_path %></li>
<li><%= link_to 'Помощь', help_path %></li>
</ul>
<!--maybe make win apps?-->
<ul class="nav secondary-nav">
<li><%= link_to 'Win', '#' %></li>
</ul>
<!--end-->
   </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SinapsIt</title>
  <%= stylesheet_link_tag 'bootstrap.css', :media => 'all' %>

  <link rel="stylesheet" href="http://twitter.github.com/bootstrap/assets/css/bootstrap-1.0.0.min.css">

  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body>
<%= render 'layouts/header' %>
<br /><br /><br /><br />
<div class="container">
<div class="page-header">
  <h1><%= @title %> </h1>
    </div>

<%= yield %>

<%= render 'layouts/footer'%>
</div>
</body>
</html>

app/views/pages/home.html.erb
<div class="row">
	<div class="span4 columns">
		<h2>Title</h2>
		<p>A team of creative people creating compelling websites for all businesse</p>
		
	</div>
	<div class="span12 columns">
		A team of creative people creating compelling websites for all businesses
		
	</div>
</div>	

app/views/pages/services.html.erb
Услуги компании